# Generated by Django 3.0.5 on 2020-05-10 21:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('plan', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='theme',
            name='language',
            field=models.CharField(choices=[('fa', 'Persian'), ('en', 'English')], default='fa', max_length=50),
        ),
        migrations.AlterField(
            model_name='theme',
            name='theme',
            field=models.CharField(choices=[('blue', 'Blue'), ('pink', 'Pink'), ('yellow', 'Yellow')], default='blue', max_length=50),
        ),
        migrations.AlterField(
            model_name='theme',
            name='username',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='plan.Profile'),
        ),
        migrations.AlterField(
            model_name='todo',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='plan.Profile'),
        ),
    ]
